version: "3"
services:
    worker:
        build: ./
    operate:
        image: camunda/operate:1.1.0
        ports:
            - "8080:8080"
        volumes:
            - "./application.yml:/usr/local/operate/config/application.yml"
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
    nginx-grpc-lb:
        image: openresty/openresty:alpine
        volumes: 
        - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
        ports:
        - "27500:26500"
    es-exporter:
       image: justwatch/elasticsearch_exporter:1.1.0
       command:
       - '--es.uri=http://elasticsearch:9200'
       - '--es.all=true'
       ports: 
       - "9114:9114"
    prometheus:
        image: prom/prometheus
        volumes:
            - "./prometheus.yml:/etc/prometheus/prometheus.yml"
        ports:
            - "9090:9090"
    broker-1:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26500:26500
            - 26501:26501
            - 5701:5701
            - 9600:9600
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_NODE_ID=0
            - ZEEBE_PARTITIONS_COUNT=48
            - ZEEBE_CLUSTER_SIZE=4
            - ZEEBE_REPLICATION_FACTOR=1
        volumes:
            - ./broker_1:/usr/local/zeebe/data
            - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    broker-2:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26510:26500
            - 9601:9600
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_NODE_ID=1
            - ZEEBE_PARTITIONS_COUNT=48
            - ZEEBE_CLUSTER_SIZE=4
            - ZEEBE_REPLICATION_FACTOR=1
            - ZEEBE_CONTACT_POINTS=broker-1:26502
        volumes:
            - ./broker_2:/usr/local/zeebe/data
            - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    broker-3:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26520:26500
            - 9602:9600
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_NODE_ID=2
            - ZEEBE_PARTITIONS_COUNT=48
            - ZEEBE_CLUSTER_SIZE=4
            - ZEEBE_REPLICATION_FACTOR=1
            - ZEEBE_CONTACT_POINTS=broker-1:26502
        volumes:
            - ./broker_3:/usr/local/zeebe/data
            - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    broker-4:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26500:26500
            - 26501:26501
            - 5701:5701
            - 9600:9600
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_NODE_ID=0
            - ZEEBE_PARTITIONS_COUNT=48
            - ZEEBE_CLUSTER_SIZE=4
            - ZEEBE_REPLICATION_FACTOR=1
        volumes:
            - ./broker_4:/usr/local/zeebe/data
            - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    elasticsearch:
        image: elasticsearch:6.7.1
        container_name: elasticsearch
        environment:
            - "discovery.type=single-node"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
            - 9300:9300 # required for Performance Analyzer
