scrape_configs:
  - job_name: brokers
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['broker-1:9600','broker-2:9600','broker-3:9600']